update from upstream

diff --git a/usr/share/initramfs-tools/scripts/casper b/usr/share/initramfs-tools/scripts/casper
--- a/usr/share/initramfs-tools/scripts/casper
+++ b/usr/share/initramfs-tools/scripts/casper
@@ -6,6 +6,7 @@ export PATH=/usr/bin:/usr/sbin:/bin:/sbin
 
 mountpoint=/cdrom
 LIVE_MEDIA_PATH=casper
+[ -f /conf/uuid.conf ] && UUID="$(cat /conf/uuid.conf)"
 
 root_persistence="casper-rw"
 home_persistence="home-rw"
@@ -37,16 +38,20 @@ parse_cmdline() {
                 export PERSISTENT="Yes" ;;
             nopersistent)
                 export PERSISTENT="" ;;
+	    persistent-path=*)
+	    	export PERSISTENT_PATH="${x#persistent-path=}" ;;
             union=*)
                 export UNIONFS="${x#union=}";;
-            ip*)
+            ip=*)
                 STATICIP=${x#ip=}
                 if [ "${STATICIP}" = "" ]; then
                     STATICIP="frommedia"
                 fi
                 export STATICIP ;;
+	   uuid=*)
+	        UUID=${x#uuid=} ;;
             ignore_uuid)
-                IGNORE_UUID="Yes" ;;
+	        UUID="" ;;
             live-media-path=*)
                 LIVE_MEDIA_PATH="${x#live-media-path=}"
                 export LIVE_MEDIA_PATH
@@ -58,7 +63,7 @@ parse_cmdline() {
         esac
     done
     if [ "${UNIONFS}" = "" ]; then
-        export UNIONFS="aufs"
+        export UNIONFS="DEFAULT"
     fi
 }
 
@@ -75,15 +80,14 @@ is_casper_path() {
 }
 
 matches_uuid() {
-    if [ "$IGNORE_UUID" ] || [ ! -e /conf/uuid.conf ]; then
+    if [ -z "$UUID" ]; then
         return 0
     fi
     path="$1"
-    uuid="$(cat /conf/uuid.conf)"
     for try_uuid_file in "$path/.disk/casper-uuid"*; do
         [ -e "$try_uuid_file" ] || continue
         try_uuid="$(cat "$try_uuid_file")"
-        if [ "$uuid" = "$try_uuid" ]; then
+	if [ "$UUID" = "$try_uuid" ]; then
             return 0
         fi
     done
@@ -128,7 +132,8 @@ mount_images_in_directory() {
 
 is_nice_device() {
     sysfs_path="${1#/sys}"
-    if /lib/udev/path_id "${sysfs_path}" | egrep -q "ID_PATH=(usb|pci-[^-]*-(ide|scsi|usb)|platform-orion-ehci|platform-mmc|platform-mxsdhci)"; then
+    #if /lib/udev/path_id "${sysfs_path}" | egrep -q "ID_PATH=(usb|pci-[^-]*-(ide|scsi|usb)|platform-orion-ehci|platform-mmc|platform-mxsdhci)"; then
+    if /sbin/udevadm test-builtin path_id "${sysfs_path}" | egrep -q "ID_PATH=(usb|pci-[^-]*-(ide|sas|scsi|usb|virtio)|platform-sata_mv|platform-orion-ehci|platform-mmc|platform-mxsdhci|platform-omap_hsmmc|platform-sdhci-tegra)"; then
         return 0
     fi
     if echo ${sysfs_path} | grep -q "^/block/dm-"; then
@@ -190,7 +195,8 @@ do_netmount() {
     /sbin/udevadm trigger
     /sbin/udevadm settle
 
-    ipconfig ${DEVICE} /tmp/net-${DEVICE}.conf | tee /netboot.config
+    configure_networking
+    export DEVICE
 
     if [ "${NFSROOT}" = "auto" ]; then
         NFSROOT=${ROOTSERVER}:${ROOTPATH}
@@ -361,15 +367,23 @@ setup_unionfs() {
     image_directory="$1"
     rootmnt="$2"
 
-    case ${UNIONFS} in
-        aufs|unionfs)
-            modprobe "${MP_QUIET}" -b ${UNIONFS} || true
-            if ! cut -f2 /proc/filesystems | grep -q "^${UNIONFS}\$" && \
-               [ -x /bin/unionfs-fuse ]; then
-                UNIONFS="unionfs-fuse"
-            fi
-            ;;
-    esac
+    if [ "${UNIONFS}" = 'DEFAULT' ]; then
+       for union in 'overlayfs' 'aufs' 'unionfs'
+       do
+            modprobe "${MP_QUIET}" -b ${union} || true
+            if cut -f2 /proc/filesystems | grep -q "^${union}\$"; then
+               UNIONFS="${union}"
+               break
+           fi
+       done
+    fi
+    if [ "${UNIONFS}" = 'DEFAULT' -a -x /bin/unionfs-fuse ]; then
+       UNIONFS="unionfs-fuse"
+    fi
+    # If all else fails fall back to aufs.
+    if [ "${UNIONFS}" = 'DEFAULT' ]; then
+       UNIONFS='aufs'
+    fi
 
     # run-init can't deal with images in a subdir, but we're going to
     # move all of these away before it runs anyway.  No, we're not,
@@ -435,9 +449,29 @@ setup_unionfs() {
             mkdir -p /dev/.initramfs/varrun
             pidof unionfs-fuse >> /dev/.initramfs/varrun/sendsigs.omit || true
             ;;
-        *)
+	aufs|unionfs)    
             mount -t ${UNIONFS} -o noatime,dirs=/cow=rw:$rofsstring ${UNIONFS} "$rootmnt" || panic "${UNIONFS} mount failed"
             ;;
+       overlayfs)
+           # Mount the layers pairwise from the bottom onto rootmnt,
+           # for the second and later layers rootmnt forms the lower layer.
+           mounts=""
+           for mount in /cow $rofslist
+           do
+               mounts="$mount $mounts"
+           done
+           lower=""
+           for mount in $mounts
+           do
+               if [ "$lower" = "" ]; then
+                   lower="$mount"
+                   continue
+               fi
+               mount -t overlayfs -o "upperdir=$mount,lowerdir=$lower" \
+                   "$mount" "$rootmnt"
+               lower="$rootmnt"
+           done
+           ;;
     esac
 
     # Adding other custom mounts
@@ -520,7 +554,7 @@ check_dev ()
         mount -t ${fstype} -o ro,noatime "${devname}" $mountpoint || continue
         [ -n "$devuid" ] && echo "$devuid" >> $tried
         if is_casper_path $mountpoint && \
-           ([ "$skip_uuid_check" ] || matches_uuid $mountpoint); then
+		([ "$skip_uuid_check" ] || [ "$UUID" = "$devuid" ] || matches_uuid $mountpoint); then
             echo $mountpoint
             return 0
         else
@@ -566,7 +600,8 @@ find_livefs() {
         elif [ "${fstype}" = "squashfs" -o \
                 "${fstype}" = "ext4" -o \
                 "${fstype}" = "ext3" -o \
-                "${fstype}" = "ext2" ]; then
+		"${fstype}" = "ext2" -o \
+		"${fstype}" = "btrfs" ]; then
             # This is an ugly hack situation, the block device has
             # an image directly on it.  It's hopefully
             # casper, so take it and run with it.
@@ -648,6 +683,18 @@ mountroot() {
     mount_images_in_directory "${livefs_root}" "${rootmnt}"
 
     log_end_msg
+
+    # Allow to override USERNAME and HOST based on media information
+    # make it skipable by setting FLAVOUR= in casper.conf
+    if [ -f /cdrom/.disk/info ] && [ -z "$FLAVOUR" ]; then
+    	FLAVOUR="$(cut -d' ' -f1 "/cdrom/.disk/info" 2>/dev/null | tr '[A-Z]' '[a-z]')" || FLAVOUR=
+    	if [ -n "$FLAVOUR" ]; then
+                HOST=$FLAVOUR
+                USERNAME=$FLAVOUR
+                export HOST USERNAME
+                sed  -i "s,USERNAME=.*,USERNAME=\"$FLAVOUR\",g; s,HOST=.*,HOST=\"$FLAVOUR\",g" /etc/casper.conf
+        fi
+    fi
 
     # unionfs-fuse needs /dev to be bind-mounted for the duration of
     # casper-bottom; udev's init script will take care of things after that
diff --git a/usr/share/initramfs-tools/scripts/casper-helpers b/usr/share/initramfs-tools/scripts/casper-helpers
--- a/usr/share/initramfs-tools/scripts/casper-helpers
+++ b/usr/share/initramfs-tools/scripts/casper-helpers
@@ -27,7 +27,7 @@ is_supported_fs () {
     # FIXME: do something better like the scan of supported filesystems
     fstype="${1}"
     case ${fstype} in
-        vfat|iso9660|udf|ext2|ext3|ext4|ntfs)
+    	vfat|iso9660|udf|ext2|ext3|ext4|btrfs|ntfs)
             return 0
             ;;
     esac
@@ -35,14 +35,14 @@ is_supported_fs () {
 }
 
 get_fstype() {
-    #yaska: /bin/fstype mistake ext4 for ext3, we only use blkid now. 
-    #local FSTYPE
-    #local FSSIZE
-    #eval $(fstype < $1)
-    #if [ "$FSTYPE" != "unknown" ]; then
-    #    echo $FSTYPE
-    #    return 0
-    #fi
+    local FSTYPE
+    local FSSIZE
+    eval $(fstype < $1)
+    if [ "$FSTYPE" != "unknown" ]; then
+      echo $FSTYPE
+      return 0
+    fi
+
     /sbin/blkid -s TYPE -o value $1 2>/dev/null
 }
 
@@ -161,6 +161,9 @@ setup_loop() {
     fi
 }
 
+# Returns 0 on success
+# panics if remount- or bind-mount fails
+# returns 1 on failure otherwise
 try_mount ()
 {
     dev="${1}"
@@ -168,19 +171,39 @@ try_mount ()
     opts="${3}"
 
     if where_is_mounted ${dev} > /dev/null; then
-    if [ "${opts}" != "ro" ]; then
-        mount -o remount,"${opts}" ${dev} $(where_is_mounted ${dev}) || panic "Remounting failed"
-    fi
+    	if [ "${opts}" != "ro" ]; then
+                mount -o remount,"${opts}" ${dev} $(where_is_mounted ${dev}) || panic "Remounting failed"
+                return 0
+        fi
         mount -o bind $(where_is_mounted ${dev}) ${mountp} || panic "Cannot bind-mount"
+	return 0
     else
-        mount -t $(get_fstype "${dev}") -o "${opts}" "${dev}" "${mountp}" || panic "Cannot mount ${dev} on ${mountp}"
+        mount -t $(get_fstype "${dev}") -o "${opts}" "${dev}" "${mountp}"
+        ret=$?
+        if [ $ret -ne 0 ]; then
+            log_warning_msg "Cannot mount ${dev} on ${mountp}"
+           return 1
+        fi
+        return 0
     fi
 }
 
 find_cow_device() {
     pers_label="${1}"
     cow_backing="/${pers_label}-backing"
+    
+    if [ -z "${PERSISTENT_PATH}" ]; then
+         pers_fpath=${pers_label}
+       else
+         pers_fpath=${PERSISTENT_PATH}/${pers_label}
+    fi
+    
     for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop); do
+	# do not ever probe floppies, probing nonexistant ones delays the boot to half an hour and longer
+	n=${sysblock##*/}
+	if [ "${n#fd}" != "$n" ]; then
+	         continue
+	fi
         for dev in $(subdevices "${sysblock}"); do
             devname=$(sys2dev "${dev}")
             if [ "$(/sbin/blkid -s LABEL -o value $devname 2>/dev/null)" = "${pers_label}" ]; then
@@ -192,12 +215,13 @@ find_cow_device() {
             # where filesystems are in use by hibernated operating systems.
             elif [ "$(get_fstype ${devname})" = "vfat" ]; then
                 mkdir -p "${cow_backing}"
-                try_mount "${devname}" "${cow_backing}" "rw"
-                if [ -e "${cow_backing}/${pers_label}" ]; then
-                    echo $(setup_loop "${cow_backing}/${pers_label}" "loop" "/sys/block/loop*")
-                    return 0
+		   try_mount "${devname}" "${cow_backing}" "rw" || continue
+		   cow_backing_mp=$(where_is_mounted "${devname}")
+		   if [ -e "${cow_backing_mp}/${pers_fpath}" ]; then
+	   	     echo $(setup_loop "${cow_backing_mp}/${pers_fpath}" "loop" "/sys/block/loop*")
+                     return 0
                 else
-                    umount ${cow_backing}
+		     umount ${cow_backing_mp}
                 fi
             fi
         done
@@ -216,7 +240,7 @@ find_files()
             devfstype="$(get_fstype ${devname})"
             if [ "${devfstype}" = "vfat" ] ||  [ "${devfstype}" = "ext2" ] ; then # FIXME: all supported block devices should be scanned
                 mkdir -p "${snap_backing}"
-                try_mount "${devname}" "${snap_backing}" "ro"
+		try_mount "${devname}" "${snap_backing}" "ro" || continue
                 for filename in ${filenames}; do
                     if [ -e "${snap_backing}/${filename}" ]; then
                         echo "${devname} ${snap_backing} ${filename}"
